version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs_auth
  redis:
    image: redis:latest
    ports:
      - 6379:6379
